name: Post JSON File to Two URLs
on:
  push:
    branches:
    - main # Runs only when pushing to the main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:4yTKVYONTS24Yz4yMeNniA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:pe0Zn-vDTbKxzsfkWanRtA/streams/AQAAAH-czlKyMkCGsuoJQx5BvT0AAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:EVT3YHaPR2eTu9wha2JNXQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:pe0Zn-vDTbKxzsfkWanRtA/streams/AQAAAMPLeSKHjkqJjgmiPcwIElcAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data to Third URL
        run: |
          curl -X POST "https://:Ibtn7pWBSvawRwEK3DYH6Q@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:pe0Zn-vDTbKxzsfkWanRtA/streams/AQAAAGFOMeDQ9UA_tzaH_nJdJwIAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json

      - name: Send JSON Data to Fourth URL
        run: |
          curl -X POST "https://:QmXW78RsQhm1JCqitGekwg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:pe0Zn-vDTbKxzsfkWanRtA/streams/AQAAAB0IsKrbREfcquhhx1UbbTsAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json
